@startuml
skinparam ConditionEndStyle hline
start
floating note left: CubeReader Validation
if (UseMeasureAccountPairs) then (no)
    if (NbAccounts * NbMeasures > 1) then (yes)
        :raise Error1>
    endif
else (yes)
    if (NbAccounts * NbMeasures != 0) then (yes)
        :raise Error2>
    else (no)
        if (NbMeasureAccountPairs == 0) then (yes)
            :raise Error3>
        endif
    endif
endif

stop

start
partition Error1 {
  :QUERY_MULTI_ACCOUNTS_AND_MEASURES_NOT_SUPPORTED_ERROR;
}
stop
start
partition Error2 {
  :QUERY_USE_MULTI_ACCOUNTS_AND_MEASURES_PAIRS_ERROR;
}
stop
start
partition Error3 {
  :QUERY_PROPERTY_ACCOUNTS_MEASURES_PAIRS_SHOULD_NODE_BE_EMPTY_ERROR;
}
stop

@enduml
