@startuml
skinparam ConditionEndStyle hline
start
floating note left: CubeReader Validation

note right
  <b>NbMeasuresAccounts</b> = CubeReader.getMeasuresAccounts().size()
  <b>NbAccounts</b> = CubeReader.getAccounts().size()
  <b>NbMeasures</b> = CubeReader.getMeasures().size()
end note
if (NbMeasuresAccounts > 0) then (no)
    if (NbAccounts * NbMeasures > 1) then (yes)
        :raise Error1>
    endif
else (yes)
    if (NbAccounts * NbMeasures != 0) then (yes)
        :raise Error2>
    endif
endif

stop

start
partition Error1 {
  :QUERY_MULTI_ACCOUNTS_AND_MEASURES_NOT_SUPPORTED_ERROR;
}
stop
start
partition Error2 {
  :QUERY_USE_MULTI_ACCOUNTS_MEASURES_API_ERROR;
}
stop


@enduml
