@startuml

interface NodeConcept

interface CubeNode extends NodeConcept {
    CubeReference getCubeReference()
    boolean getExcludeDimensionDescriptions()
}

interface Account {
    String getName();
    Account create(String name);
    List<Account> create(String... names);
}

interface Measure {
    String getName();
    Measure create(String name);
    List<Measure> create(String... names);
}

interface CubeQueryDefinition extends CubeNode {
    List<Attribute> getAttributes();
    List<Measure> getMeasures();
    List<Account> getAccounts();
    String getVersionId();
    CurrencyMode getCurrencyMode();
    List<FilterSelection> getFilterSelections();
}


interface CubeReader extends CubeQueryDefinition {
    OutputPort getOut();
}

interface PlanningCubeWriter extends CubeQueryDefinition {

    InputPort getIn();
    ColumnReference getForecast();
    ColumnReference getTargetColumn();
    ColumnReference getTime();
}

interface CubeQueryReader{
    String getQuery();
   OutputPort getOut();
}

enum Operator {
	EQUAL
}

interface Member {
	String getValue();
    @DefaultValue(Enum = "EQUAL")
	Operator getOperator();
}

interface Operand {
	
	List<Member> getMembers();
}

interface FilterSelection {

	Operand getOperand();
	
	String getDimensionName();
	String getHierarchy();
}

FilterSelection -> Operand
Member -> Operator
Operand o-> "1..*" Member
CubeQueryDefinition o-left- "0..*" Measure
CubeQueryDefinition o-down- "0..*" Account
CubeQueryDefinition o-right- "0..*" FilterSelection

CubeQueryReader -|> CubeNode
@enduml
