@startuml
skinparam ConditionEndStyle hline
start
floating note left: read activity
if (PLANNING_CHUNK_BY_ROWS) then (no)
  :Get Nb segments;
else (yes)
:Get NbRows ApplyOut;
endif


if (NbRowsOrSegments < CHUNK_SIZE) then (no)
  :calculate nbchunks;
  while (chunk < nbchunks)
    :generate chunk query;
    :call Write>
  endwhile
else (yes)
  :call Write>
endif

stop

start
floating note left: write activity
partition Write {
  :read chunk;
  :getWindowDatesForecast;
  :getSegmentDistinctValues;
  :planning generateQuery;
  while (data of chunk available?)
    :collect CellValueContext;
  endwhile

  while (CellValueContext available?)
    :update cell with CellValueContext;
  endwhile
  :submitValues;

}
stop


@enduml
